// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg0lShraFzwNBwnGIB3_M08rOg0IzpXrg',
    appId: '1:98813760476:web:33bd98297ee5c09066b519',
    messagingSenderId: '98813760476',
    projectId: 'graysta-9b670',
    authDomain: 'graysta-9b670.firebaseapp.com',
    storageBucket: 'graysta-9b670.firebasestorage.app',
    measurementId: 'G-GGK2J52QR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx-EYiVuf1Rgfg5bxAQyjPbUIMtHkcV0M',
    appId: '1:98813760476:android:cde711023c70e15466b519',
    messagingSenderId: '98813760476',
    projectId: 'graysta-9b670',
    storageBucket: 'graysta-9b670.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM_wTO4WZ_hPo9NKhwPV94uvNrMxuLEEk',
    appId: '1:98813760476:ios:34f2c3cc1fdac69166b519',
    messagingSenderId: '98813760476',
    projectId: 'graysta-9b670',
    storageBucket: 'graysta-9b670.firebasestorage.app',
    iosBundleId: 'com.patienceman.graysta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM_wTO4WZ_hPo9NKhwPV94uvNrMxuLEEk',
    appId: '1:98813760476:ios:34f2c3cc1fdac69166b519',
    messagingSenderId: '98813760476',
    projectId: 'graysta-9b670',
    storageBucket: 'graysta-9b670.firebasestorage.app',
    iosBundleId: 'com.patienceman.graysta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAg0lShraFzwNBwnGIB3_M08rOg0IzpXrg',
    appId: '1:98813760476:web:0363580d2ad5116466b519',
    messagingSenderId: '98813760476',
    projectId: 'graysta-9b670',
    authDomain: 'graysta-9b670.firebaseapp.com',
    storageBucket: 'graysta-9b670.firebasestorage.app',
    measurementId: 'G-MD27NEGCNV',
  );

}